{application,change_to_erlang,
             [{description,"A rebar plugin"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[change_to_erlang,change_to_erlang_prv]},
              {contributors,[]},
              {licenses,[]},
              {links,[]}]}.
